language: "en" # "ru" or "en"
Erroreporter: true # "true" or "false"
version: 1.81 #DO NOT CHANGE THIS PARAMETER / НЕ ИЗМЕНЯТЬ ЭТОТ ПАРАМЕТР
plugin_version: "1.81r-1.21.1" # Plugin version for webhook reports / Версия плагина для отчетов вебхука

# Настройки рандомных заданий
random_tasks:
  enabled: true # Включить рандомные задания
  difficulty: "easy" # Сложность: easy, medium, hard
  count: 1 # Количество заданий для каждого спидраннера
  auto_generate: true # Автоматически генерировать задания при старте игры
hunter:
  teleportDelay: 30 # Delay before hunter teleportation / Задержка перед телепортацией охотника
  compassgive: 120 # Time before compass is given / Время до выдачи компаса охотнику после начала игры
  giveCompassOnDeath: true # Should compass be given after hunter’s death / Выдавать ли компас после смерти охотника
  compass:
    item: COMPASS # DO NOT CHANGE THIS PARAMETER / НЕ ИЗМЕНЯТЬ ЭТОТ ПАРАМЕТР
    name: "§cHunter's Compass" # Compass name for the hunter / Название компаса для охотника
event:
  worldName: "Event" # Name of the world where the event takes place / Название мира, в котором будет проходить игра
en:
  menu:
    toggle_random:
      item: "LEVER"
      name: "§5Toggle Random Mode"
    restart_world:
      item: "ENDER_PEARL"
      name: "§6Restart Worlds"
    toggle_compass:
      item: "COMPASS"
      name: "§eToggle Nether and End Compass"
    reload_plugin:
      item: "BLUE_WOOL"
      name: "§8Reload Plugin"
    speedrunner:
      item: "LEATHER_BOOTS" # Item displayed in menu for Speedrunner selection / Предмет, отображаемый в меню для выбора Спидраннера
      name: "§9Speedrunner" # Name for Speedrunner item / Название предмета для Спидраннера
    hunter:
      item: "NETHERITE_SWORD"
      name: "§4Hunter"
    add_life:
      item: "GREEN_WOOL"
      name: "§aAdd Life"
    remove_life:
      item: "RED_WOOL"
      name: "§cRemove Life"
    start:
      item: "SPAWNER"
      name: "§eStart Game"
    setconf:
      item: "BOOK"
      name: "§7Edit Config"
    random_tasks_config:
      item: "WRITABLE_BOOK"
      name: "§5Random Tasks Config"
  messages:
    random_mode_enabled: "Random mode has been enabled!"
    random_mode_disabled: "Random mode has been disabled!"
    world_restarting: "Re-creating Worlds..."
    compass_enabled: "Compass on."
    compass_disabled: "Compass off."
    plugin_reloaded: "The plugin has been successfully reloaded!"
    only_players: "§cOnly players can execute this command."
    game_started: "§cThe game has already started."
    game_start_success: "§aThe game has started!"
    game_start_fail: "§cUnable to start the game. Ensure there are players in both teams."
    no_permission: "§cYou do not have permission to execute this command."
    game_stopped: "§cThe game has been stopped."
    game_not_started: "§cThe game has not started yet."
    selected_speedrunner: "You are now a speedrunner!"
    selected_hunter: "You are now a hunter!"
    only_speedrunner_can_add_life: "Only speedrunners can add lives!"
    only_speedrunner_can_remove_life: "Only speedrunners can remove lives!"
    start_game_op_only: "AVAILABLE TO OPERATORS ONLY!"
    not_enough_players: "Not enough players to start the game!"
    menu_closed: "Menu closed!"
    compass_received: "Your compass is back!"
    out_of_lives: "You are out of lives! You have been set to spectator mode."
    hunters_win: "Hunters Win"
    speedrunners_win: "Speedrunners Win"
    game_end: "Game end!"
    clear_ach: "§cAll achievements have been reset for all players."
    plygins: "§cPlugins reload all!"
    not_found: "§cEvent world not found! use /hunterworld to create world"
    teleport_speed: "Speedruner teleport"
    compass_give: "Giving compasses to hunters..."
    online: "Speedrunner isn't online or doesn't exist!"
    live_add: "A life has been added! Current lives: "
    live_remove: "A life has been removed! Current lives: "
    live_null: "You have run out of lives!"
    timegive: "Time before the compass is issued"
    change_language: "Language set to: "
    run_game_fast: "Starting the game..."
    teleport_delay_changed: "Teleport delay changed to: %d sec"
    compass_time_changed: "Compass time changed to: %d sec"
    give_compass_toggled_on: "Give compass on death enabled"
    give_compass_toggled_off: "Give compass on death disabled"
    advanced_settings_title: "Advanced Settings"
    language: "Language"
    teleport_delay: "Teleport Delay"
    compass_time: "Compass Time"
    give_compass_on_death: "Give compass on death"
    start_game_now: "Start the game now"
    not_take: "No one has selected this class yet!"
    reload_plugin: "Reload plugin"
    back: "Back"
    yes: "Yes"
    no: "No"
    done: "Done"
    seconds: "seconds"
    second: "second"
    random_tasks_settings: "Random Tasks Settings"
    task_difficulty: "Task Difficulty"
    easy_tasks: "Easy Tasks"
    medium_tasks: "Medium Tasks"
    hard_tasks: "Hard Tasks"
    difficulty_changed: "Difficulty changed to: %s"
    easy: "Easy"
    medium: "Medium"
    hard: "Hard"
    task_count_changed: "Task count changed to: %d"
    add_easy_to_scenario: "+ Add Easy"
    add_medium_to_scenario: "+ Add Medium"
    add_hard_to_scenario: "+ Add Hard"
    remove_last_from_scenario: "Remove Last"
    clear_scenario: "Clear"
    scenario_presets: "Presets"
    task_scenario_summary: "Task Scenario"
    scenario_empty: "The script is empty. A random preset will be selected."
    scenario_pieces: "Pieces in execution order:"
    easy_added: "Added: Easy task to template."
    medium_added: "Added: Medium task to template."
    hard_added: "Added: Hard task to template."
    scenario_cleared: "Task template cleared."
    last_piece_removed: "Last piece removed from template."
    scenario_already_empty: "Template is already empty."
    preset_applied: "Preset applied!"
    tasks_category_title: "Tasks"
    category_inventory: "Inventory"
    category_kill: "Kill"
    category_tnt: "TNT"
    category_enchant: "Enchant"
    category_effect: "Effect"
    category_achievement: "Achievement"
    add_task_button: "+ Add Task"
    task_list_title: "Tasks %s"
    kill_task_display: "Kill: %s"
    collect_task_display: "Collect: %s"
    effect_task_display: "Effect: %s"
    achievement_task_display: "Achievement: %s"
    item_enchant_display: "Item: %s"
    enchants_label: "Enchants: %s"
    task_added: "Task added: %s → %s"
    enchant_task_added: "Added item '%s' with enchants: %s"
    save_error: "Save error: %s"
    scenario_presets_title: "Scenario Presets"
    preset_1h1m1e: "1H + 1M + 1E"
    preset_3e: "3E"
    preset_2m: "2M"
    preset_2h: "2H"
    preset_2e1m: "2E + 1M"
    preset_1e2m: "1E + 2M"
    preset_1h2e: "1H + 2E"
    preset_3m: "3M"
    preset_3h: "3H"
    kill_ender_dragon: "KILL ENDER DRAGON"
    # Random task bossbar templates
    task_collect: "Collect %d× %s"
    task_kill: "Kill %d× %s"
    task_effects: "Gain effects: %s"
    task_achievements: "Unlock achievements: %s"
    task_enchant: "Enchant %s with: %s"

  # Names used inside random task descriptions (you can extend this list)
  task_names:
    materials:
      unknown: "Unknown"
      diamond_pickaxe: "Diamond Pickaxe"
      diamond_sword: "Diamond Sword"
      diamond_axe: "Diamond Axe"
      diamond_shovel: "Diamond Shovel"
      diamond_hoe: "Diamond Hoe"
      enchanting_table: "Enchanting Table"
    mobs:
      zombie: "Zombie"
      skeleton: "Skeleton"
      spider: "Spider"
      creeper: "Creeper"
      cow: "Cow"
      pig: "Pig"
      sheep: "Sheep"
      chicken: "Chicken"
      drowned: "Drowned"
      rabbit: "Rabbit"
    effects:
      invisibility: "Invisibility"
    enchants:
      efficiency: "Efficiency"
      unbreaking: "Unbreaking"
      fortune: "Fortune"
      silk_touch: "Silk Touch"
    advancements:
      story/obtain_armor: "Obtain Armor"
ru:
  menu:
    toggle_random:
      item: "LEVER"
      name: "§5Включить рандомный режим"
    restart_world:
      item: "ENDER_PEARL"
      name: "§6Пересоздать миры"
    toggle_compass:
      item: "COMPASS"
      name: "§eАктивировать компас во всех мирах"
    reload_plugin:
      item: "BLUE_WOOL"
      name: "§8Перезапустить плагин"
    speedrunner:
      item: "LEATHER_BOOTS" # Предмет, отображаемый в меню для выбора Спидраннера / Item displayed in menu for Speedrunner selection
      name: "§9Спидранер" # Название предмета для Спидраннера / Name for Speedrunner item
    hunter:
      item: "NETHERITE_SWORD"
      name: "§4Хантер"
    add_life:
      item: "GREEN_WOOL"
      name: "§aДобавить жизнь"
    remove_life:
      item: "RED_WOOL"
      name: "§cУбрать жизнь"
    start:
      item: "SPAWNER"
      name: "§eНачать игру"
    setconf:
      item: "BOOK"
      name: "§7Редактировать конфиг"
    random_tasks_config:
      item: "WRITABLE_BOOK"
      name: "§5Настройки заданий"
  messages:
    random_mode_enabled: "Рандомный режим включен!"
    random_mode_disabled: "Рандомный режим выключен!"
    world_restarting: "Пересоздание миров..."
    plugin_reloaded: "Плагин успешно перезагружен!"
    only_players: "§cТолько игроки могут выполнять эту команду."
    game_started: "§cИгра уже началась."
    game_start_success: "§aИгра началась!"
    game_start_fail: "§cНевозможно начать игру. Убедитесь, что в обеих командах есть игроки."
    no_permission: "§cУ вас нет прав на выполнение этой команды."
    game_stopped: "§cИгра была остановлена."
    game_not_started: "§cИгра еще не началась."
    selected_speedrunner: "Вы теперь спидраннер!"
    selected_hunter: "Вы теперь хантер!"
    only_speedrunner_can_add_life: "Только спидраннеры могут добавлять жизни!"
    only_speedrunner_can_remove_life: "Только спидраннеры могут убирать жизни!"
    start_game_op_only: "Доступно только операторам!"
    not_enough_players: "Недостаточно игроков для начала игры!"
    menu_closed: "Меню закрыто!"
    compass_received: "Вам вернулся компас!"
    out_of_lives: "У вас закончились жизни! Вы переведены в режим наблюдателя."
    hunters_win: "Победили хантеры"
    speedrunners_win: "Спидранеры победили"
    game_end: "Игра окончена!"
    clear_ach: "§cВсе достижения были сброшены для всех игроков"
    plygins: "§cПлагины были презагружены"
    not_found: "§cМир не был обнаружен, используйте /hunterworld что бы создать мир"
    teleport_speed: "Телепортирование спидранеров"
    compass_give: "Выдача компаса хантерам..."
    online: "Спидранер не подключен к сети или не существует!"
    live_add: "Жизнь была добавлена! Текущие жизни:"
    live_remove: "Жизнь была удалена! Текущие жизни:"
    live_null: "У вас закончились жизни!"
    timegive: "Время до выдачи компаса"
    compass_enabled: "Компас включен."
    compass_disabled: "Компас выключен."
    change_language: "Язык установлен на: "
    run_game_fast: "Игра запускается..."
    teleport_delay_changed: "Задержка телепорта изменена на: %d сек"
    compass_time_changed: "Время до компаса изменено на: %d сек"
    give_compass_toggled_on: "Компас после смерти включен"
    give_compass_toggled_off: "Компас после смерти отключен"
    advanced_settings_title: "Расширенные настройки"
    language: "Язык"
    teleport_delay: "Задержка телепорта"
    compass_time: "Время до компаса"
    give_compass_on_death: "Компас после смерти"
    start_game_now: "Стартовать игру сейчас"
    reload_plugin: "Перезагрузить плагин"
    not_take: "Пока никто не выбрал этот класс!"
    back: "Назад"
    yes: "Да"
    no: "Нет"
    done: "Готово"
    seconds: "сек"
    second: "секунда"
    random_tasks_settings: "Настройки рандомных заданий"
    task_difficulty: "Сложность заданий"
    easy_tasks: "Легкие задания"
    medium_tasks: "Средние задания"
    hard_tasks: "Сложные задания"
    difficulty_changed: "Сложность изменена на: %s"
    easy: "Легкая"
    medium: "Средняя"
    hard: "Сложная"
    task_count_changed: "Количество заданий изменено на: %d"
    add_easy_to_scenario: "+ Лёгкое"
    add_medium_to_scenario: "+ Среднее"
    add_hard_to_scenario: "+ Сложное"
    remove_last_from_scenario: "↩ Убрать последний"
    clear_scenario: "✖ Очистить"
    scenario_presets: "★ Пресеты"
    task_scenario_summary: "Сценарий задач"
    scenario_empty: "Сценарий пуст. Будет выбран случайный пресет."
    scenario_pieces: "Кусочки в порядке выполнения:"
    easy_added: "Добавлено: Лёгкое задание в шаблон."
    medium_added: "Добавлено: Среднее задание в шаблон."
    hard_added: "Добавлено: Сложное задание в шаблон."
    scenario_cleared: "Шаблон задач очищен."
    last_piece_removed: "Убран последний кусочек из шаблона."
    scenario_already_empty: "Шаблон уже пуст."
    preset_applied: "Пресет применён!"
    tasks_category_title: "Задания"
    category_inventory: "Inventory"
    category_kill: "Kill"
    category_tnt: "TNT"
    category_enchant: "Enchant"
    category_effect: "Effect"
    category_achievement: "Achievement"
    add_task_button: "+ Добавить задание"
    task_list_title: "Задачи %s"
    kill_task_display: "Убить: %s"
    collect_task_display: "Собрать: %s"
    effect_task_display: "Эффект: %s"
    achievement_task_display: "Достижение: %s"
    item_enchant_display: "Предмет: %s"
    enchants_label: "Чары: %s"
    task_added: "Добавлено задание: %s → %s"
    enchant_task_added: "Добавлен предмет '%s' с чарами: %s"
    save_error: "Ошибка сохранения: %s"
    scenario_presets_title: "Пресеты сценариев"
    preset_1h1m1e: "1H + 1M + 1E"
    preset_3e: "3E"
    preset_2m: "2M"
    preset_2h: "2H"
    preset_2e1m: "2E + 1M"
    preset_1e2m: "1E + 2M"
    preset_1h2e: "1H + 2E"
    preset_3m: "3M"
    preset_3h: "3H"
    kill_ender_dragon: "УБИТЬ ЭНДЕР ДРАКОНА"
    # Шаблоны текста рандомных заданий (боссбар)
    task_collect: "Собрать %d× %s"
    task_kill: "Убить %d× %s"
    task_effects: "Получить эффекты: %s"
    task_achievements: "Получить достижения: %s"
    task_enchant: "Зачаровать %s на: %s"

  # Названия, используемые в описаниях заданий (можно расширять)
  task_names:
    materials:
      unknown: "Неизвестно"
      diamond_pickaxe: "Алмазная кирка"
      diamond_sword: "Алмазный меч"
      diamond_axe: "Алмазный топор"
      diamond_shovel: "Алмазная лопата"
      diamond_hoe: "Алмазная мотыга"
      enchanting_table: "Стол зачарований"
    mobs:
      zombie: "Зомби"
      skeleton: "Скелет"
      spider: "Паук"
      creeper: "Крипер"
      cow: "Корова"
      pig: "Свинья"
      sheep: "Овца"
      chicken: "Курица"
      drowned: "Утопленник"
      rabbit: "Кролик"
    effects:
      invisibility: "Невидимость"
    enchants:
      efficiency: "Эффективность"
      unbreaking: "Прочность"
      fortune: "Удача"
      silk_touch: "Шёлковое касание"
    advancements:
      story/obtain_armor: "Надеть броню"